### ISSUE TITLE
New Scolarship Entity and Sections

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#455]
We need to create a new entity on the website for scollarships, the idea is to have a folder inside data: `./src/data/sholarship` that contains one .yml file for each scholarhip agreement that we have, for example, we already have scolarships for womans who code, bridges unite, etc.

./src/data/scholarship/miami-whoman-who-code.us.yml
./src/data/scholarship/madrid-bridges-unite.es.yml

Inside the YML we need to have this fields:
```
utm_location: downtown-miami | madrid-spain, etc..
utm_course: full-stack | full-stack-ft | software-engineering
partner: 
    logo_url:
    name:
    etc...
```

The landing page must have a small for to request more information (use the same LeadForm plugin that we al ready use).

Here is an example of the landing page: https://www.ironhack.com/en/social-impact/vinted-scholarship

# Landing page

Then we need a landing page where you can pick your location and it will display the lists of scholarships that we offer similar to this list:
https://campaigns.wyncode.co/scholarships/
