### ISSUE TITLE
Seccion de FAQ

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#498]
hrs: <hrs>12</hrs>

**Comment by plucodev** [comment]
@ArielCalisaya  need to use Grid and Div instead Row-Column

**Comment by alesanchezr** [comment]
Cambia la estructura del YML para que puedas tener topicos asi:

```yml
faq:
  - topic: "Preguntas Frecuentes sobre 4Geeks"
    questions:
      - question: "¿Do I need to have my own laptop?"
        answer: "The simple and quick answer is YES! You will need to bring your computer to class, we don’t require a specific operating system because the classes and exercises are uploaded to the cloud."
      - question: "Is 4Geeks a certified institution?"
        answer: "For sure! We are licensed (not accredited) in Florida by the Commission for Independent Education of the Florida Department of Education"
  - topic: "Preguntas Frecuentes sobre Inscriciones"
    questions:
      - question: "¿Do I need to have my own laptop?"
        answer: "The simple and quick answer is YES! You will need to bring your computer to class, we don’t require a specific operating system because the classes and exercises are uploaded to the cloud."
      - question: "Is 4Geeks a certified institution?"
        answer: "For sure! We are licensed (not accredited) in Florida by the Commission for Independent Education of the Florida Department of Education"
```
